name: AutoMerge Dependabot

on:
  pull_request:

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn workspace @tumi/server build:production

      - name: Run Tests
        run: yarn workspace @tumi/legacy-app ng build

  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.MYTOKEN }}
          command: squash and merge
